config/routes.rb
RaisonMentors20::Application.routes.draw do
  
  devise_for :admins, :skip => [:registrations]   
    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'    
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'            
    end
    
  devise_for :clients, :skip => [:registrations]     #stops clients/organisations registering on their own. We register them.                                     
    as :client do
      get 'clients/edit' => 'devise/registrations#edit', :as => 'edit_client_registration'    
      put 'clients' => 'devise/registrations#update', :as => 'client_registration'            
    end

  devise_for :members, controllers: { confirmations: 'confirmations' }

  
  
post "application/apply_mentor" => "application#mentor"
post "application/apply_project" => "application#project"
resources :application, :collection => { :apply_mentor => :post, :apply_project => :post }
  

  match "about_us/" => "about_us#index"

  get "about_us/how_it_works"

  get "about_us/our_philosophy"

  get "about_us/meet_the_team"
  get "pages/add_a_project"
  get "pages/become_a_mentor"
  get "pages/privacy_policy"

  get "pages/terms_of_use"
  
  get "pages/terms_and_conditions"

  get "pages/contact_us"
  post "pages/send_email" => "pages#send_email"
  get "pages/confirmation"

  get "pages/register"

  get "pages/home"
  
  get "members/sign_out"
  match "members/profile", :to => "members#profile", :as => :member
  get "members/settings"
  get "members/applications" 
  get "members/" => "members#dashboard"
  get "members/dashboard"
  put "members/update" => "members#update"
  get "members/new_mentor" 
  post "members/create_mentor" =>"members#create_mentor"
  get "members/edit_mentor"
  get "members/destroy_mentor"
  put "members/create_mentor" => "members#update_mentor"
  get "members/list_internal_mentors"
  match "members/mentors/search" => "members#search_mentor"
  get "members/list_projects"
  match "members/projects/search" => "members#search_project"
  get "members/edit_project"
  match "members/edit_project/:id/:name" => "members#edit_project"
  put "members/edit_project" => "members#update_project"
  get "members/new_project"
  post "members/create_project" => "members#create_project"
  
  get "clients/settings"
  put "clients/settings" => "clients#update_client"
  get "clients/list_projects"
  get "clients/new_project"
  post "clients/create_project" => "clients#create_project"
  get "clients/edit_project"
  match "clients/edit_project/:id/:name" => "clients#edit_project"  
  put "clients/edit_project" => "clients#update_project"
  get "clients/list_mentors"

  get "clients/new_mentor"
  post "clients/create_mentor" => "clients#create_mentor"
  get "clients/edit_mentor"
  match "clients/edit_mentor/:id/:fname" => "clients#edit_mentor"
  put "clients/edit_mentor" => "clients#update_mentor"
  get "clients/list_jobs"

  get "clients/add_job"

  get "clients/edit_job"

  get "clients/dashboard" 

  get "clients/profile"
  post "clients/profile_update" => "clients#profile_update"
  put "clients/profile_update" => "clients#profile_update"

  get "admin/login" => "admin#dashboard"
  get "admin/dashboard"
  get "admin/settings"
  put "admin/settings" => "admin#update_admin"
  get "admin/profile"
  post "admin/profile_update" => "admin#profile_update"
  put "admin/profile_update" => "admin#profile_update"
  get "admin/dashboard/download/:id" => "admin#download"
  get "admin/list_projects"
  get "admin/new_project"
  post "admin/create_project" => "admin#create_project"
  get "admin/edit_project"
  match "admin/edit_project/:id/:name" => "admin#edit_project"  
  put "admin/edit_project" => "admin#update_project"
  get "admin/list_mentors"
  get "admin/new_mentor"
  post "admin/create_mentor" => "admin#create_mentor"
  get "admin/edit_mentor"
  match "admin/edit_mentor/:id/:fname" => "admin#edit_mentor"
  put "admin/edit_mentor" => "admin#update_mentor"
  get "admin/list_employer_profiles"
  get "admin/new_employer_profile"
  post "admin/create_employer_profile" => "admin#create_employer_profile"
  get "admin/edit_employer_profile"
  match "admin/edit_employer_profile/:id" => "admin#edit_employer_profile"
  put "admin/update_employer_profile/:id" => "admin#update_employer_profile" 
  get "admin/new_member"
  post "admin/create_member" => "admin#create_member"
  get "admin/edit_member/"
  match "admin/edit_member/:id" => "admin#edit_member"
  put "admin/update_member/:id" => "admin#update_member" 
  get "admin/list_members"
  get "admin/list_members/reset_password/:id" => "admin#member_password_reset"
  get "admin/new_client" => "admin#new_client"
  post "admin/create_client" => "admin#create_client"
  get "admin/edit_client/"
  match "admin/edit_client/:id" => "admin#edit_client"
  put "admin/update_client/:id" => "admin#update_client" 
  get "admin/list_clients"
  delete 'admin/destroy_client/:id' => 'admin#destroy_client'  
  get "admin/adverts"
  get "admin/team"
  get "admin/new_organisation_email" => "admin#new_organisation_email"
  post "admin/create_organisation_email" => "admin#create_organisation_email"
  get "admin/edit_organisation_email"
  match "admin/edit_organisation_email/:id" => "admin#edit_organisation_email"
  put "admin/update_organisation_email/:id" => "admin#update_organisation_email" 
  get "admin/list_organisation_emails"
  get "admin/destroy_organisation_email/:id" => "admin#destroy_organisation_email"
  delete "admin/destroy_organisation_email/:id" => "admin#destroy_organisation_email"
  get "admin/new_sector" => "admin#new_sector"
  post "admin/create_sector" => "admin#create_sector"
  get "admin/edit_sector"
  match "admin/edit_sector/:id" => "admin#edit_sector"
  put "admin/update_sector/:id" => "admin#update_sector" 
  get "admin/list_sectors"
  get "admin/destroy_sector/:id" => "admin#destroy_sector"
  delete "admin/destroy_sector/:id" => "admin#destroy_sector"
  get "admin/new_location" => "admin#new_location"
  post "admin/create_location" => "admin#create_location"
  get "admin/edit_location"
  match "admin/edit_location/:id" => "admin#edit_location"
  put "admin/update_location/:id" => "admin#update_location" 
  get "admin/list_locations"
  get "admin/destroy_location/:id" => "admin#destroy_location"
  delete "admin/destroy_location/:id" => "admin#destroy_location"
  
  
  get "employers/search" => "employer_profiles#search"
  post "employers/search" => "employer_profiles#search"
  resources :employer_profiles

  resources :teams

  resources :adverts

  get "projects/search" => "projects#search"
  resources :projects
  post "projects/apply" => "projects#apply"
  post "projects/search" => "projects#search"

  get "mentors/search" => "mentors#search"
  resources :mentors
  post "mentors/apply" => "mentors#apply"
  post "mentors/search" => "mentors#search"

  root :to => 'pages#home'

end

app/views/admin/_location_form.html.erb
<%= form_for(@location,url: {action: @action_address},html: { class: "blocks"}) do |f| %>
<div id="tab1" class="tab_content">
	<%= f.text_field :name, :placeholder => "Location name", :class=>"text" %>
</div>
<br/><br/>
<%= f.submit "Update", :style => "width: 21em"%>
<% end %>

app/views/admin/_project_form.html.erb
	<%= form_for(@project,url: {action: @action_address},html: {id:"form_add_project", class: "blocks"}) do |f| %>
	<%= f.hidden_field :id %>
					<div id="tab1" class="tab_content">
						<table>
							 <tr>
							    <td><%= f.label :name, 'Project Name' %></td>
							    <td><%= f.text_field :name, :class=>"text" %></td>
							   </tr>
							 <tr>
							    <td><%= f.label :project_leader %></td>
							    <td><%= f.text_field :project_leader,:class=>"text" %></td>
							   </tr>
							 <tr>
							    <td><%= f.label :organisation %></td>
							    <td><%= f.text_field :organisation,:class=>"text"%></td>
						   </tr>
							 <tr>
							    <td><%= f.label :sector_ids, 'Works in (select max 3)' %></td>
								<td><%= f.select "sector_ids", options_from_collection_for_select(@sectors, "id", "name",  @project_sectors_ids) ,{}, {:multiple => true, :style => "background: white; width:242px;"} %></td>
							   </tr>
							 
							 <tr>
							    <td><%= f.label :location %></td>
							    <td><%= f.select :location, Location.all.collect {|l| [l.name, l.name]},{}, {:class=>"text", :style=> "width:242px"} %>
							   </tr>
							 <tr>
							    <td><%= f.label :description %></td>
							    <td><%= f.text_area :description,:class=>"textarea" %></td>
							   </tr>
					 	</table>
				 	</div>
					<div id="tab2" class="tab_content">
						<table>
							<tr>
							    <td><%= f.label :email %></td>
							    <td><%= f.text_field :email,:class=>"text" %></td>
							   </tr>
							 <tr>
							    <td><%= f.label :telephone %></td>
							    <td><%= f.text_field :telephone,:class=>"text" %></td>
							   </tr>
						</table>
				 	</div>	   
				 	<div id="tab3" class="tab_content">
						<table>
							   <tr>
							    <td><%= f.label :closing_date %></td>
							    <td><%= f.text_field :closing_date, :class => "text", :id=>"datepicker_future", :readonly =>true%>
							   </tr>
							   <tr>
									<td><%= f.label :image %></td>
									<td><%= f.file_field :image %></td>
									<td>Currenty: <%= image_tag @project.image.to_s, :style=>"width: 106px" if !@project.image.blank?%></td>
								</tr>
								<tr>
									<td></td>
									<td></td>
									<td>Remove Image?: <%= f.check_box :remove_image %></td>
								</tr>
						</table>				
					</div>
					<% #TODO create validatin client.
					%> 
					<div class ="submit_link">
						<%= f.submit :onclick => "return validateProjectForm();" %>
					</div>
					<% end %>

app/views/admin/edit_employer_profile.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
			<h4 class="alert_info">This is where you can view and edit your company profile.</h4>
	
			<article class="module width_full" style="border:none; background:transparent;">
		
				<ul class="tabs">
		   			<li><a href="#tab1">Company Details</a></li>
		    		<li><a href="#tab2">Other</a></li>
				</ul>

				<div class="tab_container" style="clear:both; padding: 5% 0 0 5%;">
					<%= render 'employer_profile_form' %>
				</div>
			</article>
		</section>

app/views/admin/edit_member.html.erb
	<%= javascript_include_tag "admins" %>
	<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>
	
	<%= render :partial => 'shared/admin/header' %>
	<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
	
	<section id="main" class="column">
	<%= render :partial => 'shared/member/alerts_and_notices'%>
	<article class="module width_full" style="border:none; background:transparent;">
		
		<%= render :partial => 'member_form'%>
		
			</article>
	</section>

app/views/admin/edit_project.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
	
			<article class="module width_full" style="border:none; background:transparent;">
		
				<ul class="tabs">
		   			<li><a href="#tab1">Project Details</a></li>
		    		<li><a href="#tab2">Contact Details</a></li>
		    		<li><a href="#tab3">Other</a></li>
				</ul>

				<div class="tab_container" style="clear:both; padding: 5% 0 0 5%;">
					<%= render 'project_form' %>
				</div>
			</article>
		</section>

app/views/admin/list_clients.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

<script type="text/javascript">  
        $(document).ready(function(){
            $("#details tr:odd").addClass("odd");
            $("#details tr:not(.odd)").hide();
            $("#details tr:first-child").show();
            
            $("#details tr.odd").click(function(){
                $(this).next("tr").toggle();
                $(this).find(".arrow").toggleClass("up");
            });
            //$("#details").jExpand();
        });
    </script>        

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
				<article class="module width_full" style="border:none; background:transparent;">			
					<h1>Listing clients</h1>
					
					<table id="details">
					  <tr>
					  	<th>ID</th>
					    <th>Name</th>
					    <th>Email</th>
					    <!--<th>Sectors</th> -->
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>
					
					<% @clients.each do |client| %>
					  <tr>
					  	<td><%= client.id%></td>
					    <td><%= client.organisation %></td>
					    <td><%= client.email %></td>
					    <!-- <td><%= #sectorsHTML(client)  
					    %></td> -->
					    <td><%= link_to 'Edit', admin_edit_client_path + "/#{client.id}" %>
					    </td>
					    <td><%= button_to 'Delete', '/admin/destroy_client' + "/#{client.id}", method: :delete, data: { confirm: 'Are you sure?' }, :style=> "background: none;  border: none; box-shadow: none;" 
					    %></td>
					    <td><div class="arrow"></div></td>
					  </tr>
					  <tr>
					  	<td colspan="11">
					  		<div class="inner">
				  			</div>
					  	</td>
					  </tr>
					<% end %>
					</table>
					
					<br />
					
			</article>
		</section>
		
<% #TODO FIND A WAY TO USE POST METHOD WHEN GOIG TO EDIT PAGE 
%>

app/views/admin/list_members.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

<script type="text/javascript">  
        $(document).ready(function(){
            $("#details tr:odd").addClass("odd");
            $("#details tr:not(.odd)").hide();
            $("#details tr:first-child").show();
            
            $("#details tr.odd").click(function(){
                $(this).next("tr").toggle();
                $(this).find(".arrow").toggleClass("up");
            });
            //$("#details").jExpand();
        });
    </script>        

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
				<article class="module width_full" style="border:none; background:transparent;">			
					<h1>Listing members</h1>
					
					<table id="details">
					  <tr>
					  	<th>ID</th>
					    <th>First Name</th>
					    <th>Last Name</th>
					    <th>Email</th>
					    <th>Sectors</th>
					    <th>Confirmation sent at</th>
					    <th>Confirmed at</th>
					    <th>Singed in count</th>
					    <th>Reset Passowrd (For Sid only)</th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>
					
					<% @members.each do |member| %>
					  <tr>
					  	<td><%= member.id%></td>
					    <td><%= member.fname %></td>
					    <td><%= member.lname %></td>
					    <td><%= member.email %></td>
					    <td><%= sectorsHTML(member) %></td>
					    <td><%= member.confirmation_sent_at %></td>
					    <td><%= member.confirmed_at%></td>
					    <td><%= member.sign_in_count%></td>
					    <td><%= link_to 'Reset', "/admin/list_members/reset_password/#{member.id}" %></td>
					    <td><%= # link_to 'Edit', admin_edit_member_path + "/#{member.id}" 
					    %>
					    </td>
					    <td><%= button_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' }, :style=> "background: none;  border: none; box-shadow: none;" %></td>
					    <td><div class="arrow"></div></td>
					  </tr>
					  <tr>
					  	<td colspan="11">
					  		<div class="inner">
					  			<p><span>DOB: </span><%= member.dob %></p>
							    <p><span>Gender: </span><%= member.gender %></p>
						    	<p><span>Course: </span><%= member.course %></p>
							    <p><span>Telephone: </span><%= member.telephone %></p>
				  				<p><span>Location: </span><%= locationHTML(member) %></p>
				  				<p><spam>CV: </span><%= member.cv %></p>
				  			</div>
					  	</td>
					  </tr>
					<% end %>
					</table>
					
					<br />
					
			</article>
		</section>
		

app/views/admin/list_mentors.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

<script type="text/javascript">  
        $(document).ready(function(){
            $("#details tr:odd").addClass("odd");
            $("#details tr:not(.odd)").hide();
            $("#details tr:first-child").show();
            
            $("#details tr.odd").click(function(){
                $(this).next("tr").toggle();
                $(this).find(".arrow").toggleClass("up");
            });
            //$("#details").jExpand();
        });
    </script>        

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
				<article class="module width_full" style="border:none; background:transparent;">			
					<h1>Listing mentors</h1>
					
					<table id="details">
					  <tr>
					    <th>First Name</th>
					    <th>Last Name</th>
					    <th>Role title</th>
					    <th>Sectors</th>
					    <th>Organisation</th>
					    <th>Closing Date</th>
					 <!--    -->
					    <th>Draft</th>
					    <th></th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>
					
					<% @mentors.each do |mentor| %>
					  <tr>
					    <td><%= mentor.fname %></td>
					    <td><%= mentor.lname %></td>
					    <td><%= mentor.role_title %></td>
					    <td><%= sectorsHTML(mentor) %></td>
					    <td><%= mentor.organisation %></td>
					    <td><%= mentor.closing_date %></td>
					    <td><%= mentor.draft %></td>
					    <td><%= link_to 'Show', mentor %></td>
					    <td><%= link_to 'Edit', admin_edit_mentor_path + "/#{mentor.id}/#{mentor.fname}" %>
					    	<!--<a href="#" onClick="document.myForm.id.value='<%= mentor.id %>';this.href='javascript:submitForm()'">Hello World</a> -->
					    </td>
					    <td><%= button_to 'Delete', mentor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					    <td><div class="arrow"></div></td>
					  </tr>
					  <tr>
					  	<td colspan="11">
					  		<div class="inner">
				  				<p><span>Location: </span><%= mentor.location %></p>
							 <!--   <p><span>Description: </span><%= mentor.description %></p> -->
							    <p><span>Email: </span><%= mentor.email %></p>
							    <p><span>Telephone: </span><%= mentor.telephone %></p>
							    <p><span>Image: </span><%= mentor.image %></p>
							    <p><span>Applications made: </span> <%= countMentorApplications(mentor.id)%></p>
				  			</div>
					  	</td>
					  </tr>
					<% end %>
					</table>
					
					<br />
					
			</article>
		</section>
		
<% #TODO FIND A WAY TO USE POST METHOD WHEN GOIG TO EDIT PAGE 
%>

app/views/admin/list_organisation_emails.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

<script type="text/javascript">  
        $(document).ready(function(){
            $("#details tr:odd").addClass("odd");
            $("#details tr:not(.odd)").hide();
            $("#details tr:first-child").show();
            
            $("#details tr.odd").click(function(){
                $(this).next("tr").toggle();
                $(this).find(".arrow").toggleClass("up");
            });
            //$("#details").jExpand();
        });
    </script>        

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
				<article class="module width_full" style="border:none; background:transparent;">			
					<h1>Listing clients</h1>
					
					<table id="details">
					  <tr>
					  	<th>ID</th>
					    <th>Organisation</th>
					    <th>Email Domain</th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>
					
					<% @oes.each do |oe| %>
					  <tr>
					  	<td><%= oe.id%></td>
					    <td><%= oe.organisation %></td>
					    <td><%= oe.domain %></td>
					    <td><%= link_to 'Edit', admin_edit_organisation_email_path + "/#{oe.id}" %>
					    </td>
					    <td><%= link_to 'Delete', "/admin/destroy_organisation_email" + "/#{oe.id}", method: :delete, data: { confirm: 'Are you sure?' } 
					    %></td>
					    <td><div class="arrow"></div></td>
					  </tr>
					  <tr>
					  	<td colspan="11">
					  		<div class="inner">
				  			</div>
					  	</td>
					  </tr>
					<% end %>
					</table>
					
					<br />
					
			</article>
		</section>
		
<% #TODO FIND A WAY TO USE POST METHOD WHEN GOIG TO EDIT PAGE 
%>

app/views/admin/login.html.erb
<h1>Admin#login</h1>
<p>Find me in app/views/admin/login.html.erb</p>

app/views/admin/new_client.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
	
			<article class="module width_full" style="border:none; background:transparent;">
		
				<ul class="tabs">
		   			<li><a href="#tab1">Organisation Details</a></li>
		    		<li><a href="#tab2">Security</a></li>
		    		<li><a href="#tab3">Sign Up!</a></li>
				</ul>

				<div class="tab_container" style="clear:both; padding: 5% 0 0 5%;">
					<%= render 'client_form' %>
				</div>
			</article>
		</section>

app/views/admin/new_employer_profile.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
			<h4 class="alert_info">This is where you can view and edit your company profile.</h4>
	
			<article class="module width_full" style="border:none; background:transparent;">
		
				<ul class="tabs">
		   			<li><a href="#tab1">Company Details</a></li>
		    		<li><a href="#tab2">Other</a></li>
				</ul>

				<div class="tab_container" style="clear:both; padding: 5% 0 0 5%;">
					<%= render 'employer_profile_form' %>
				</div>
			</article>
		</section>

app/views/admin/new_location.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
	
			<article class="module width_full" style="border:none; background:transparent;">
		
				<ul class="tabs">
		   			<li><a href="#tab1">Location Details</a></li>
				</ul>

				<div class="tab_container" style="clear:both; padding: 5% 0 0 5%;">
					<%= render 'location_form' %>
				</div>
			</article>
		</section>

app/views/admin/new_organisation_email.html.erb
<%= javascript_include_tag "admin" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/admin/header' %>
<%= render :partial => 'shared/admin/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
	
			<article class="module width_full" style="border:none; background:transparent;">
		
				<ul class="tabs">
		   			<li><a href="#tab1">Organisation Details</a></li>
				</ul>

				<div class="tab_container" style="clear:both; padding: 5% 0 0 5%;">
					<%= render 'organisation_email_form' %>
				</div>
			</article>
		</section>