config/routes.rb
RaisonMentors20::Application.routes.draw do
  
  devise_for :admins, :skip => [:registrations]   
    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'    
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'            
    end
    
  devise_for :clients, :skip => [:registrations]     #stops clients/organisations registering on their own. We register them.                                     
    as :client do
      get 'clients/edit' => 'devise/registrations#edit', :as => 'edit_client_registration'    
      put 'clients' => 'devise/registrations#update', :as => 'client_registration'            
    end

  devise_for :members, controllers: { confirmations: 'confirmations' }

  
  
post "application/apply_mentor" => "application#mentor"
post "application/apply_project" => "application#project"
resources :application, :collection => { :apply_mentor => :post, :apply_project => :post }
  

  match "about_us/" => "about_us#index"

  get "about_us/how_it_works"

  get "about_us/our_philosophy"

  get "about_us/meet_the_team"
  get "pages/add_a_project"
  get "pages/become_a_mentor"
  get "pages/privacy_policy"

  get "pages/terms_of_use"
  
  get "pages/terms_and_conditions"

  get "pages/contact_us"
  post "pages/send_email" => "pages#send_email"
  get "pages/confirmation"

  get "pages/register"

  get "pages/home"
  
  get "members/sign_out"
  match "members/profile", :to => "members#profile", :as => :member
  get "members/settings"
  get "members/applications" 
  get "members/" => "members#dashboard"
  get "members/dashboard"
  put "members/update" => "members#update"
  get "members/new_mentor" 
  post "members/create_mentor" =>"members#create_mentor"
  get "members/edit_mentor"
  get "members/destroy_mentor"
  put "members/create_mentor" => "members#update_mentor"
  get "members/list_internal_mentors"
  match "members/mentors/search" => "members#search_mentor"
  get "members/list_projects"
  match "members/projects/search" => "members#search_project"
  get "members/edit_project"
  match "members/edit_project/:id/:name" => "members#edit_project"
  put "members/edit_project" => "members#update_project"
  get "members/new_project"
  post "members/create_project" => "members#create_project"
  
  get "clients/settings"
  put "clients/settings" => "clients#update_client"
  get "clients/list_projects"
  get "clients/new_project"
  post "clients/create_project" => "clients#create_project"
  get "clients/edit_project"
  match "clients/edit_project/:id/:name" => "clients#edit_project"  
  put "clients/edit_project" => "clients#update_project"
  get "clients/list_mentors"

  get "clients/new_mentor"
  post "clients/create_mentor" => "clients#create_mentor"
  get "clients/edit_mentor"
  match "clients/edit_mentor/:id/:fname" => "clients#edit_mentor"
  put "clients/edit_mentor" => "clients#update_mentor"
  get "clients/list_jobs"

  get "clients/add_job"

  get "clients/edit_job"

  get "clients/dashboard" 

  get "clients/profile"
  post "clients/profile_update" => "clients#profile_update"
  put "clients/profile_update" => "clients#profile_update"

  get "admin/login" => "admin#dashboard"
  get "admin/dashboard"
  get "admin/settings"
  put "admin/settings" => "admin#update_admin"
  get "admin/profile"
  post "admin/profile_update" => "admin#profile_update"
  put "admin/profile_update" => "admin#profile_update"
  get "admin/dashboard/download/:id" => "admin#download"
  get "admin/list_projects"
  get "admin/new_project"
  post "admin/create_project" => "admin#create_project"
  get "admin/edit_project"
  match "admin/edit_project/:id/:name" => "admin#edit_project"  
  put "admin/edit_project" => "admin#update_project"
  get "admin/list_mentors"
  get "admin/new_mentor"
  post "admin/create_mentor" => "admin#create_mentor"
  get "admin/edit_mentor"
  match "admin/edit_mentor/:id/:fname" => "admin#edit_mentor"
  put "admin/edit_mentor" => "admin#update_mentor"
  get "admin/list_employer_profiles"
  get "admin/new_employer_profile"
  post "admin/create_employer_profile" => "admin#create_employer_profile"
  get "admin/edit_employer_profile"
  match "admin/edit_employer_profile/:id" => "admin#edit_employer_profile"
  put "admin/update_employer_profile/:id" => "admin#update_employer_profile" 
  get "admin/new_member"
  post "admin/create_member" => "admin#create_member"
  get "admin/edit_member/"
  match "admin/edit_member/:id" => "admin#edit_member"
  put "admin/update_member/:id" => "admin#update_member" 
  get "admin/list_members"
  get "admin/list_members/reset_password/:id" => "admin#member_password_reset"
  get "admin/new_client" => "admin#new_client"
  post "admin/create_client" => "admin#create_client"
  get "admin/edit_client/"
  match "admin/edit_client/:id" => "admin#edit_client"
  put "admin/update_client/:id" => "admin#update_client" 
  get "admin/list_clients"
  delete 'admin/destroy_client/:id' => 'admin#destroy_client'  
  get "admin/adverts"
  get "admin/team"
  get "admin/new_organisation_email" => "admin#new_organisation_email"
  post "admin/create_organisation_email" => "admin#create_organisation_email"
  get "admin/edit_organisation_email"
  match "admin/edit_organisation_email/:id" => "admin#edit_organisation_email"
  put "admin/update_organisation_email/:id" => "admin#update_organisation_email" 
  get "admin/list_organisation_emails"
  get "admin/destroy_organisation_email/:id" => "admin#destroy_organisation_email"
  delete "admin/destroy_organisation_email/:id" => "admin#destroy_organisation_email"
  get "admin/new_sector" => "admin#new_sector"
  post "admin/create_sector" => "admin#create_sector"
  get "admin/edit_sector"
  match "admin/edit_sector/:id" => "admin#edit_sector"
  put "admin/update_sector/:id" => "admin#update_sector" 
  get "admin/list_sectors"
  get "admin/destroy_sector/:id" => "admin#destroy_sector"
  delete "admin/destroy_sector/:id" => "admin#destroy_sector"
  get "admin/new_location" => "admin#new_location"
  post "admin/create_location" => "admin#create_location"
  get "admin/edit_location"
  match "admin/edit_location/:id" => "admin#edit_location"
  put "admin/update_location/:id" => "admin#update_location" 
  get "admin/list_locations"
  get "admin/destroy_location/:id" => "admin#destroy_location"
  delete "admin/destroy_location/:id" => "admin#destroy_location"
  
  
  get "employers/search" => "employer_profiles#search"
  post "employers/search" => "employer_profiles#search"
  resources :employer_profiles

  resources :teams

  resources :adverts

  get "projects/search" => "projects#search"
  resources :projects
  post "projects/apply" => "projects#apply"
  post "projects/search" => "projects#search"

  get "mentors/search" => "mentors#search"
  resources :mentors
  post "mentors/apply" => "mentors#apply"
  post "mentors/search" => "mentors#search"

  root :to => 'pages#home'

end

app/views/shared/_admin_footer.html.erb
<footer>
	<hr />
	<p><strong>Copyright &copy; 2013 Raison Mentors</strong></p>
	<p>Developed by Sidhant Mehta</p>
</footer>

app/views/shared/_footer.html.erb
<%#:TODO change all href links. Change columns to what we actually need. %>
<footer>
	<div class=" container_24">
		<div class="wrapper">
			<div class="grid_6 suffix_2"> <!-- Column 1 -->
				<h1 class="footer-logo"><h1 style="font-size: 2em; font-family: impact;color: white;width: 7em;line-height: 40px; margin-top: -10px;">Raison Mentors</h1></h1>
				<p style="color:white;">Love <span style="color: lightsteelblue;">work.</span> Love <span style="color: lightsteelblue;">life.</span></p>
				<p class="color1 privacy">&copy; 2012 <span>|</span>  <a href= <%= pages_privacy_policy_path %>>Privacy Policy</a> <span>|</span> <a href=<%= pages_terms_and_conditions_path  %>>Terms and Conditions</a> <span>|</span><a href=<%= pages_terms_of_use_path%>>Terms of Use</a></p>
			</div>
			<div class="grid_7 suffix_2"> <!-- Column 2 -->
				<div class="wrapper">
					<div class="grid_4 alpha"> <!-- Column 2.1 -->
						<ul class="footer-list">
						</ul>
					</div>
					<div class="grid_3 omega"> <!-- Column 2.2 -->
						<ul class="footer-list">
						</ul>
					</div>
				</div>
			</div>
			<div class="grid_7"> <!-- Column 3 -->
				<h4>Follow Us</h4>
				<ul class="tooltips">
					<li><a href="http://uk.linkedin.com/groups/Raison-Mentors-4830630"><%= image_tag ("icon1.png")%><span>LinkedIn</span></a></li>
					<li><a href="https://www.facebook.com/pages/Raison-Mentors/269390666513607"><%= image_tag ("icon3.png")%><span>Facebook</span></a></li>
					<li><a href="https://twitter.com/RaisonMentors"><%= image_tag ("icon2.png")%><span>Twitter</span></a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_homepage_slider.html.erb
<div class="pad-slider">
	<div class="main-slider">
		<ul class="items">
			<li>
				<%= image_tag ("Slide1.jpg")%>
								<div style="display:none" class="slider-banner"><span></span></div>

			</li>
			<li>
				<%= image_tag ("Slide2.jpg")%>

			</li>
			<li>
				<%= image_tag ("Slide3.jpg")%>

			</li>
			<li>
				<%= image_tag ("Slide4.jpg")%>

			</li>
		</ul>
	</div>
</div>

app/views/shared/_navigation.html.erb
<%#TODO fix all the a href tags to link_to rails tags with correct naems. %>
<nav class="main-menu">
	<ul class="sf-menu">
		<li><em><%=link_to "About Us", about_us_path %></em><strong></strong>  <!-- class="current" -->
			<ul>
				<li><%=link_to "How it works", about_us_how_it_works_path %></li>
				<li><%=link_to "Meet the team", about_us_meet_the_team_path %></li>
				<li><%=link_to "Our philosophy", about_us_our_philosophy_path%></li>
			</ul>
		</li>
		<li><em><%=link_to "Mentors", mentors_path %></em><strong></strong>
			<ul>
				<li><%=link_to "Find a mentor", mentors_search_path %></li>
				<li><%=link_to "Become a mentor", pages_become_a_mentor_path %></li><!-- look at team html-->
			</ul>
		</li>
		<li><em><%=link_to "Projects", projects_path %></em><strong></strong>  <!-- class="current" -->
			<ul>
				<li><%=link_to "Find a project", projects_search_path %></li><!-- look at services.html-->
				<li><%=link_to "Add a project", pages_add_a_project_path %></li><!-- look at team html-->
			</ul>
		</li>
		<li><em><%=link_to "Organisations A-Z", employer_profiles_path %></em><strong></strong></li>
		<li class="last"><em><%= link_to "Contact us", pages_contact_us_path%></em><strong></strong></li>
		
		<% if member_signed_in? == false && client_signed_in? == false && admin_signed_in? == false %>
		<li><em class="nav_button">Login</em><strong></strong>
			<ul>
				<li><%= link_to "members", members_dashboard_path %></li>
				<li><%= link_to "organisations", clients_dashboard_path %></li>
			</ul> 
		</li>
		<% end%>
		<% if member_signed_in? %>
		<li><em class="nav_button">Members</em><strong></strong>
			<ul>
				<li><%= link_to "dashboard", members_dashboard_path %></li>
				<li><%= link_to "logout", destroy_member_session_path, :method => :delete %></li>
			</ul> 
		</li>
		<% end%>
		<% if client_signed_in? %>
		<li><em class="nav_button">Organisations</em><strong></strong>
			<ul>
				<li><%= link_to "dashboard", clients_dashboard_path %></li>
				<li><%= link_to "logout", destroy_client_session_path, :method => :delete %></li>
			</ul> 
		</li>
		<% end%>
		<% if admin_signed_in? %>
		<li><em class="nav_button">Admin</em><strong></strong>
			<ul>
				<li><%= link_to "dashboard", admin_dashboard_path %></li>
				<li><%= link_to "logout", destroy_admin_session_path, :method => :delete %></li>
			</ul> 
		</li>
		<% end%>
		
	</ul>
	<div class="clear"></div>
</nav>

app/views/shared/_searchbar.html.erb
<link rel="stylesheet"href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<div class="tabs-vert-left">
	<ul class="tabs-nav">
		<li>
			<a href="">Search</a>
		</li>
		<li>
			<a href="">Advanced</a>
		</li>
	</ul>
	<%= form_tag('/'+@type+'s/search', :id=> 'form')%>
	<div class="tab-content">
		<div class="container_24">
			<div class="wrapper">
				<div class="grid_12">
					<label> <span class="text-form fleft">Industry:</span> <%= select_tag('sector_id', options_from_collection_for_select(@sectors, "id", "name"), :include_blank=>true)%> </label>
				</div>
				<div class="grid_12">
					<label>Location: </label><%= select_tag('location', options_from_collection_for_select(@location, "name", "name"), :include_blank=>true)%>
					<% if (@type != @type)%>
					<div class="grid_12" style="width: 50%;">
						<label for="amount">Min Salary (£):</label>
						<div style="" class="pay_slider" id="pay_slider"></div>
						<%= text_field_tag('pay_value', nil, :class => "pay_value", :id  => "pay_value")%>
					</div>
					<% end%>
				</div>
				<%= submit_tag('Search', :class => "button")%>
			</div>
		</div>
	</div>

	<div class="tab-content" style="display: block;">
		<div class="container_24">
			<div class="wrapper">
				<% if (@type != "employer") %>
				<div class="grid_12">
					<label >Closing before:</label>
					<input class="closing_date" id="closing_date" name="closing_date" readonly="readonly" type="text" class="hasDatepicker">
				</div>
				<% end %>
				<div class="grid_12">
					<%= text_field_tag(@type+'_name', nil, :placeholder => "#{@type}'s name...", :id=>@type+'_name')%>
				</div>
				<%= submit_tag('Search', :class => "button")%>
			</div>
		</div>
	</div>

</div>

</form>

<script>
	$("#closing_date").datepicker({
		dateFormat : "dd-mm-yy"
	});

	var steps = ["Expenses only", "100", "200", "300", "400+"];

	$(function() {
		$("#pay_slider").slider({
			value : 0,
			min : 0,
			max : 4,
			slide : function(event, ui) {
				$("#pay_value").val(steps[ui.value]);
			}
		});
		$("#pay_value").val(steps[$("#pay_slider").slider("value")]);
	});

</script>