config/routes.rb
RaisonMentors20::Application.routes.draw do
  
  devise_for :admins, :skip => [:registrations]   
    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'    
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'            
    end
    
  devise_for :clients, :skip => [:registrations]     #stops clients/organisations registering on their own. We register them.                                     
    as :client do
      get 'clients/edit' => 'devise/registrations#edit', :as => 'edit_client_registration'    
      put 'clients' => 'devise/registrations#update', :as => 'client_registration'            
    end

  devise_for :members, controllers: { confirmations: 'confirmations' }

  
  
post "application/apply_mentor" => "application#mentor"
post "application/apply_project" => "application#project"
resources :application, :collection => { :apply_mentor => :post, :apply_project => :post }
  

  match "about_us/" => "about_us#index"

  get "about_us/how_it_works"

  get "about_us/our_philosophy"

  get "about_us/meet_the_team"
  get "pages/add_a_project"
  get "pages/become_a_mentor"
  get "pages/privacy_policy"

  get "pages/terms_of_use"
  
  get "pages/terms_and_conditions"

  get "pages/contact_us"
  post "pages/send_email" => "pages#send_email"
  get "pages/confirmation"

  get "pages/register"

  get "pages/home"
  
  get "members/sign_out"
  match "members/profile", :to => "members#profile", :as => :member
  get "members/settings"
  get "members/applications" 
  get "members/" => "members#dashboard"
  get "members/dashboard"
  put "members/update" => "members#update"
  get "members/new_mentor" 
  post "members/create_mentor" =>"members#create_mentor"
  get "members/edit_mentor"
  get "members/destroy_mentor"
  put "members/create_mentor" => "members#update_mentor"
  get "members/list_internal_mentors"
  match "members/mentors/search" => "members#search_mentor"
  get "members/list_projects"
  match "members/projects/search" => "members#search_project"
  get "members/edit_project"
  match "members/edit_project/:id/:name" => "members#edit_project"
  put "members/edit_project" => "members#update_project"
  get "members/new_project"
  post "members/create_project" => "members#create_project"
  
  get "clients/settings"
  put "clients/settings" => "clients#update_client"
  get "clients/list_projects"
  get "clients/new_project"
  post "clients/create_project" => "clients#create_project"
  get "clients/edit_project"
  match "clients/edit_project/:id/:name" => "clients#edit_project"  
  put "clients/edit_project" => "clients#update_project"
  get "clients/list_mentors"

  get "clients/new_mentor"
  post "clients/create_mentor" => "clients#create_mentor"
  get "clients/edit_mentor"
  match "clients/edit_mentor/:id/:fname" => "clients#edit_mentor"
  put "clients/edit_mentor" => "clients#update_mentor"
  get "clients/list_jobs"

  get "clients/add_job"

  get "clients/edit_job"

  get "clients/dashboard" 

  get "clients/profile"
  post "clients/profile_update" => "clients#profile_update"
  put "clients/profile_update" => "clients#profile_update"

  get "admin/login" => "admin#dashboard"
  get "admin/dashboard"
  get "admin/settings"
  put "admin/settings" => "admin#update_admin"
  get "admin/profile"
  post "admin/profile_update" => "admin#profile_update"
  put "admin/profile_update" => "admin#profile_update"
  get "admin/dashboard/download/:id" => "admin#download"
  get "admin/list_projects"
  get "admin/new_project"
  post "admin/create_project" => "admin#create_project"
  get "admin/edit_project"
  match "admin/edit_project/:id/:name" => "admin#edit_project"  
  put "admin/edit_project" => "admin#update_project"
  get "admin/list_mentors"
  get "admin/new_mentor"
  post "admin/create_mentor" => "admin#create_mentor"
  get "admin/edit_mentor"
  match "admin/edit_mentor/:id/:fname" => "admin#edit_mentor"
  put "admin/edit_mentor" => "admin#update_mentor"
  get "admin/list_employer_profiles"
  get "admin/new_employer_profile"
  post "admin/create_employer_profile" => "admin#create_employer_profile"
  get "admin/edit_employer_profile"
  match "admin/edit_employer_profile/:id" => "admin#edit_employer_profile"
  put "admin/update_employer_profile/:id" => "admin#update_employer_profile" 
  get "admin/new_member"
  post "admin/create_member" => "admin#create_member"
  get "admin/edit_member/"
  match "admin/edit_member/:id" => "admin#edit_member"
  put "admin/update_member/:id" => "admin#update_member" 
  get "admin/list_members"
  get "admin/list_members/reset_password/:id" => "admin#member_password_reset"
  get "admin/new_client" => "admin#new_client"
  post "admin/create_client" => "admin#create_client"
  get "admin/edit_client/"
  match "admin/edit_client/:id" => "admin#edit_client"
  put "admin/update_client/:id" => "admin#update_client" 
  get "admin/list_clients"
  delete 'admin/destroy_client/:id' => 'admin#destroy_client'  
  get "admin/adverts"
  get "admin/team"
  get "admin/new_organisation_email" => "admin#new_organisation_email"
  post "admin/create_organisation_email" => "admin#create_organisation_email"
  get "admin/edit_organisation_email"
  match "admin/edit_organisation_email/:id" => "admin#edit_organisation_email"
  put "admin/update_organisation_email/:id" => "admin#update_organisation_email" 
  get "admin/list_organisation_emails"
  get "admin/destroy_organisation_email/:id" => "admin#destroy_organisation_email"
  delete "admin/destroy_organisation_email/:id" => "admin#destroy_organisation_email"
  get "admin/new_sector" => "admin#new_sector"
  post "admin/create_sector" => "admin#create_sector"
  get "admin/edit_sector"
  match "admin/edit_sector/:id" => "admin#edit_sector"
  put "admin/update_sector/:id" => "admin#update_sector" 
  get "admin/list_sectors"
  get "admin/destroy_sector/:id" => "admin#destroy_sector"
  delete "admin/destroy_sector/:id" => "admin#destroy_sector"
  get "admin/new_location" => "admin#new_location"
  post "admin/create_location" => "admin#create_location"
  get "admin/edit_location"
  match "admin/edit_location/:id" => "admin#edit_location"
  put "admin/update_location/:id" => "admin#update_location" 
  get "admin/list_locations"
  get "admin/destroy_location/:id" => "admin#destroy_location"
  delete "admin/destroy_location/:id" => "admin#destroy_location"
  
  
  get "employers/search" => "employer_profiles#search"
  post "employers/search" => "employer_profiles#search"
  resources :employer_profiles

  resources :teams

  resources :adverts

  get "projects/search" => "projects#search"
  resources :projects
  post "projects/apply" => "projects#apply"
  post "projects/search" => "projects#search"

  get "mentors/search" => "mentors#search"
  resources :mentors
  post "mentors/apply" => "mentors#apply"
  post "mentors/search" => "mentors#search"

  root :to => 'pages#home'

end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :organisation, :password, :password_confirmation, :remember_me, :unconfirmed_email
  # attr_accessible :title, :body
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_filter :authenticate_client!
    before_filter :setVars
    layout 'admin'
 #---------LOCAL METHODS ------------------
def clean_select_multiple_params hash = params
  hash.each do |k, v|
    case v
    when Array
       v.reject!(&:blank?)
       v.join(',')
    when Hash then clean_select_multiple_params(v)
    end
  end
end  
  
 def setVars
    @sectors= Sector.find(:all, :order => "name")
=begin
    Sector.all.each_with_index do |s,i|
      @sectors << Sector.find(s)
    end
=end
end 
  
def getMentorApplications(client_org)
  @mentor_application_data = Mentor.select("member_mentor_applications.mentor_id, mentors.fname, mentors.lname, member_mentor_applications.id, member_mentor_applications.created_at, member_mentor_applications.status").joins("JOIN member_mentor_applications ON mentors.id = member_mentor_applications.mentor_id").where('mentors.organisation = ?', client_org)
  return @mentor_application_data
end

def getProjectApplications(client_org)
  @project_applicatoin_data = Project.select("member_project_applications.project_id, projects.name, member_project_applications.id, member_project_applications.created_at, member_project_applications.status").joins("JOIN member_project_applications ON projects.id = member_project_applications.project_id").where('projects.organisation = ?', client_org)
end
  
  
#---- END LOCAL METHDOS ---------------------  
  
  def list_projects
      if (EmployerProfile.exists?(current_client.id) && !EmployerProfile.find(current_client.id).name.blank?)
        org = OrganisationEmailDomain.getOrganisation current_client.email
        @projects = Project.where(:organisation => org)
        @sectors = Sector.find(:all, :order=>'name')
        
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @project }
        end

    else
        respond_to do |format|
              format.html {redirect_to clients_profile_path, alert:"You must complete your profile before adding, editing or viewing any Mentors or Projects."}
          end
    end
  end

  def new_project
    @action_address = "create_project"
    if (EmployerProfile.exists?(current_client.id) && !EmployerProfile.find(current_client.id).name.blank?)
        @project = Project.new
        @project.organisation = OrganisationEmailDomain.getOrganisation current_client.email
        #@project_sectors_ids = {}
        #@project.email = current_client.email
        @sectors = []
        Sector.all.each_with_index do |s,i|
            @sectors << Sector.find(s)
          end
        
        respond_to do |format|
          format.html
          format.json {render json: @project}
        end
    else
        respond_to do |format|
          format.html {redirect_to clients_profile_path, alert:"You must complete your profile before adding, editing or viewing any Mentors or Projects."}
        end
    end
  end
  
  def create_project
    @action_address = "create_project"
    p = clean_select_multiple_params params[:project]
    p["sector_ids"] = p["sector_ids"].join(',')
    @project = Project.new(p)
    @project.skip_email_check = true
    @project.user = current_client
    
    @sectors = []
        Sector.all.each_with_index do |s,i|
            @sectors << Sector.find(s)
          end
          
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        @error_str = ""
        @project.errors.each do |field, msg|
              @error_str = @error_str + "<p>" + msg + "</p>"
        end
        
        flash.now[:alert] = @error_str.html_safe
        
        format.html { render action: "new_project" }
      end
    end
  end

  def edit_project
    @action_address = "update_project"
    @project = Project.find(params[:id])
    
     if @project.sector_ids.blank?
     else   
        @project_sectors_ids_array = @project.sector_ids.split(",")
        @project_sectors_ids = [] #need to initialize this array first
         @project_sectors_ids_array.each_with_index do |s, i| 
           @project_sectors_ids << Sector.find(s).id
     end
    end
  end

  def update_project
    @action_address = "update_project"
    p = clean_select_multiple_params params[:project]
    p["sector_ids"] = p["sector_ids"].join(',')
    
    @project = Project.find(p["id"])
    @project.skip_email_check = true
    @project.user = current_client
    
    @sectors = []
    Sector.all.each_with_index do |s,i|
        @sectors << Sector.find(s)
      end
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        @error_str = ""
        @project.errors.each do |field, msg|
              @error_str = @error_str + "<p>" + msg + "</p>"
        end
        
        flash.now[:alert] = @error_str.html_safe
        
        format.html { render action: "edit_project" }
      end
    end
  end

  def list_mentors
    if (EmployerProfile.exists?(current_client.id) && !EmployerProfile.find(current_client.id).name.blank?)
        @mentors = Mentor.where(:organisation => EmployerProfile.find(current_client.id).name)
        @sectors = Sector.find(:all, :order=>'name')
        
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @mentors }
        end

    else
        respond_to do |format|
              format.html {redirect_to clients_profile_path, alert:"You must complete your profile before adding, editing or viewing any Mentors or Projects."}
          end
    end

  end

  def new_mentor
    @action_address = "create_mentor"
    if (EmployerProfile.exists?(current_client.id) && !EmployerProfile.find(current_client.id).name.blank?)
          @mentor = Mentor.new
          @mentor.organisation = EmployerProfile.find(current_client.id).name
          @sectors=[]
          Sector.all.each_with_index do |s,i|
            @sectors << Sector.find(s)
          end
          
          respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @mentor }
          end
    else
          respond_to do |format|
              format.html {redirect_to clients_profile_path, alert:"You must complete your profile before adding, editing or viewing any Mentors or Projects."}
          end
    end

  end

  # POST /create_mentor
  # POST /create_mentor.json
  def create_mentor
    @action_address = "create_mentor"
    m = clean_select_multiple_params params[:mentor]
    m["sector_ids"] = m["sector_ids"].join(',')
    @mentor = Mentor.new(m)
    @mentor.skip_email_check = true
    @mentor.user = current_client
    
     if @mentor.sector_ids.blank?
     else   
        @mentor_sectors_ids_array = @mentor.sector_ids.split(",")
        @mentor_sectors_ids = [] #need to initialize this array first
         @mentor_sectors_ids_array.each_with_index do |s, i| 
           @mentor_sectors_ids << Sector.find(s).id
     end
    end
    
    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
        format.json { render json: @mentor, status: :created, location: @mentor }
      else
        @error_str = ""
        @mentor.errors.each do |field, msg|
              @error_str = @error_str + "<p>" + msg + "</p>"
        end
        
        flash.now[:alert] = @error_str.html_safe
        
        format.html { render action: "new_mentor" }
        #format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /mentors/1/edit
  def edit_mentor
    @action_address = "update_mentor"
    @mentor = Mentor.find(params[:id])
    
     if @mentor.sector_ids.blank?
     else   
        @mentor_sectors_ids_array = @mentor.sector_ids.split(",")
        @mentor_sectors_ids = [] #need to initialize this array first
         @mentor_sectors_ids_array.each_with_index do |s, i| 
           @mentor_sectors_ids << Sector.find(s).id
     end
    end
  end

  def update_mentor
    @action_address = "update_mentor"
      m = clean_select_multiple_params params[:mentor]
      m["sector_ids"] = m["sector_ids"].join(',')

      @mentor = Mentor.find(m["id"])
      @mentor.skip_email_check = true
      @mentor.user = current_client
      
     if @mentor.sector_ids.blank?
     else   
        @mentor_sectors_ids_array = @mentor.sector_ids.split(",")
        @mentor_sectors_ids = [] #need to initialize this array first
         @mentor_sectors_ids_array.each_with_index do |s, i| 
           @mentor_sectors_ids << Sector.find(s).id
     end
    end
       
       
    respond_to do |format|
      if @mentor.update_attributes(params[:mentor])
        format.html { redirect_to @mentor, notice: 'Mentor was successfully updated.' }
        format.json { head :no_content }
      else
        @error_str = ""
        @mentor.errors.each do |field, msg|
          @error_str = @error_str + "<p>" + msg + "</p>"
        end
        flash[:alert] = @error_str.html_safe
        
        format.html { render action: "edit_mentor"}
      end
    end
  end
  
  def list_jobs
  end

  def add_job
  end

  def edit_job
  end

  def dashboard
    org = OrganisationEmailDomain.getOrganisation(current_client.email)
    @mentor_application_data = getMentorApplications(org)
    @project_application_data = getProjectApplications(org)
    @limit = 10
    
  end

  def profile # employer profile
    #get the employer profile record that is already in place. Or create a new one which has the same organisation name as the current client, as this one client is responsible for the company.
    

app/helpers/clients_helper.rb
module ClientsHelper



end

app/views/clients/dashboard.html.erb
	<%= render :partial => 'shared/client/header' %>
	<%= render :partial => 'shared/client/secondarybar_and_sidebar'%>
	
		<section id="main" class="column">
		<%= render :partial => 'shared/member/alerts_and_notices'%>
		<h4 class="alert_info">Welcome to your dashboard! This is where you can view, edit and add mentors, projects and jobs for your company.</h4>
		
		<!-- start of table -->
		<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Recent Applications</h3>
		<ul class="tabs">
   			<li><a href="#tab1">Mentors</a></li>
    		<li><a href="#tab2">Projects</a></li>
    		<li><a href="#tab3">Jobs</a></li>
		</ul>
		</header>

		<!-- tab 1--> 
		<div class="tab_container">
			<div id="tab1" class="tab_content">
			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th>Application ID</th>
    				<th>Mentor Name</th> 
    				<th>Status</th> 
    				<th>Created On</th> 
    				<!--<th>Actions</th> --> 
				</tr>
			</thead> 
			<tbody> 
				<% @mentor_application_data.take(@limit).each_with_index do |application,index| %> 
				<tr> 
					<%  %> 
   					<td><%= application.id%></td> 
    				<td><%= link_to "#{application.fname} #{application.lname}", mentors_path + "/" + application.mentor_id.to_s %></td> 
    				<td><%= application.status%></td> 
    				<td><%= application.created_at.strftime("%d %b %Y - %H:%M") %></td> 
    				<!--<td><%= image_submit_tag("admin/icn_edit.png", :title => "Edit") %><%= image_submit_tag("admin/icn_trash.png", :title => "Trash") %> -->
				</tr> 
				<% end %>
			</tbody> 
			</table>
			</div><!-- end of #tab1 -->
		
		<!-- tab 2--> 	
			<div id="tab2" class="tab_content">
			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th>Application ID</th>
    				<th>Project Name</th> 
    				<th>Status</th> 
    				<th>Created On</th> 
    				<!--<th>Actions</th> --> 
				</tr>
			</thead> 
			<tbody> 
				<% @project_application_data.take(@limit).each_with_index do |application,index| %> 
				<tr> 
					<%  %> 
   					<td><%= application.id%></td> 
    				<td><%= link_to "#{application.name}", projects_path + "/" + application.project_id.to_s %></td> 
    				<td><%= application.status%></td> 
    				<td><%= application.created_at.strftime("%d %b %Y - %H:%M") %></td> 
    				<!--<td><%= image_submit_tag("admin/icn_edit.png", :title => "Edit") %><%= image_submit_tag("admin/icn_trash.png", :title => "Trash") %> -->
				</tr> 
				<% end %>
							</tbody> 
			</table>

			</div><!-- end of #tab2 -->
			
			<!-- tab 3--> 	
			<div id="tab3" class="tab_content">
			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th>Coming Soon</th> 
				</tr> 
			</thead> 
			<tbody> 
			</tbody> 
			</table>

			</div><!-- end of #tab3 -->
			
		</div><!-- end of .tab_container -->
		
		</article><!-- end of content manager article -->
		
	</aside><!-- end of sidebar -->
	
	<!-- latest updates area -->
	<% if false %>
	<article class="module width_quarter">
			<header><h3>Messages</h3></header>
			<div class="message_list">
				<div class="module_content">
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
				</div>
			</div>
			<footer>
		</article><!-- end of messages article -->
	<% end %>
	</section> <!-- end of column section (at top) -->

app/views/clients/edit_job.html.erb
<h1>Clients#edit_job</h1>
<p>Find me in app/views/clients/edit_job.html.erb</p>

app/views/clients/list_jobs.html.erb
<h1>Clients#list_jobs</h1>
<p>Find me in app/views/clients/list_jobs.html.erb</p>

app/views/clients/list_mentors.html.erb
<%= javascript_include_tag "clients" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/client/header' %>
<%= render :partial => 'shared/client/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

<script type="text/javascript">  
        $(document).ready(function(){
            $("#details tr:odd").addClass("odd");
            $("#details tr:not(.odd)").hide();
            $("#details tr:first-child").show();
            
            $("#details tr.odd").click(function(){
                $(this).next("tr").toggle();
                $(this).find(".arrow").toggleClass("up");
            });
            //$("#details").jExpand();
        });
    </script>        

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
				<article class="module width_full" style="border:none; background:transparent;">			
					<h1>Listing mentors</h1>
					
					<table id="details">
					  <tr>
					    <th>First Name</th>
					    <th>Last Name</th>
					    <th>Role title</th>
					    <th>Sectors</th>
					    <th>Organisation</th>
					    <th>Closing Date</th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>
					
					<% @mentors.each do |mentor| %>
					  <tr>
					    <td><%= mentor.fname %></td>
					    <td><%= mentor.lname %></td>
					    <td><%= mentor.role_title %></td>
					    <td><%= sectorsHTML(mentor) %></td>
					    <td><%= mentor.organisation %></td>
					    <td><%= mentor.closing_date %></td>
					    <td><%= link_to 'Show', mentor %></td>
					   <%if false%> 
					    <td><%= link_to 'Edit', clients_edit_mentor_path + "/#{mentor.id}/#{mentor.fname}" %>
					    </td>
					    <%end%>
					    <td><%# link_to 'Delete', mentor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					    <td><div class="arrow"></div></td>
					  </tr>
					  <tr>
					  	<td colspan="11">
					  		<div class="inner">
				  				<p><span>Location: </span><%= mentor.location %></p>
							 <!--   <p><span>Description: </span><%= mentor.description %></p> -->
							    <p><span>Email: </span><%= mentor.email %></p>
							    <p><span>Telephone: </span><%= mentor.telephone %></p>
							    <p><span>Image: </span><%= mentor.image %></p>
							    <p><span>Applications made: </span><%= countMentorApplications(mentor.id)%></p>
				  			</div>
					  	</td>
					  </tr>
					<% end %>
					</table>
					
					<br />
					
			</article>
		</section>

app/views/clients/list_projects.html.erb
<%= javascript_include_tag "clients" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/client/header' %>
<%= render :partial => 'shared/client/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

<script type="text/javascript">  
        $(document).ready(function(){
            $("#details tr:odd").addClass("odd");
            $("#details tr:not(.odd)").hide();
            $("#details tr:first-child").show();
            
            $("#details tr.odd").click(function(){
                $(this).next("tr").toggle();
                $(this).find(".arrow").toggleClass("up");
            });
            //$("#details").jExpand();
        });
    </script>        

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
				<article class="module width_full" style="border:none; background:transparent;">			
					<h1>Listing projects</h1>

					<table id="details">
					  <tr>
					    <th>Name</th>
					    <th>Project leader</th>
					    <th>Sectors</th>
					    <th>Organisation</th>
					    <th>Closing date</th>
					    <th></th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>
					
					<% @projects.each do |project| %>
					  <tr>
					    <td><%= project.name %></td>
					    <td><%= project.project_leader %></td>
					    <td><%= sectorsHTML(project) %></td>
					    <td><%= project.organisation %></td>
					    <td><%= project.closing_date %></td>
					    <td><%= link_to 'Show', project %></td>
					    <td><%= link_to 'Edit', clients_edit_project_path + "/#{project.id}/#{project.name}" %></td>
					    <td><%= link_to 'Remove', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					    <td><div class="arrow"></div></td>
					  </tr>
					  <tr>
					  	<td colspan="10">
				  			<div class="inner">
				  				<p><span>Location:</span> <%= project.location %></p>
							    <p><span>Description:</span> <%= project.description %></p>
							    <p><span>Email:</span> <%= project.email %></p>
							    <p><span>Telephone:</span> <%= project.telephone %></p>
							    <p><span>Applications made: </span><%= countProjectApplications(project.id)%></p>
				  			</div>
				  		</td>
					  </tr>
					<% end %>
					</table>
					
					<br />
			</article>
		</section>
		
<% #TODO FIND A WAY TO USE POST METHOD WHEN GOIG TO EDIT PAGE 
%>

<script language="JavaScript"><!--
function submitForm() {
    document.myForm.commit.click();
}
//--></script>

app/views/clients/settings.html.erb
<%= javascript_include_tag "clients" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render :partial => 'shared/client/header' %>
<%= render :partial => 'shared/client/secondarybar_and_sidebar'%>
<%= stylesheet_link_tag "validation/validation_default", :type => "text/css", :media => "screen"%>

		<section id="main" class="column">
			<%= render :partial => 'shared/member/alerts_and_notices'%>
	
			<article class="module width_full" style="border:none; background:transparent;">
				<%= button_to "Edit email address or password.", edit_client_registration_path, :method => :get %>
			</article>
		</section>